### ISSUE TITLE
Network Error when saving settings (v0.1.0)

### ISSUE THREAD

**Issue by seveibar** [moufette-tools/moufette#19]
Here's a recording of the issue. https://www.loom.com/share/097c1609db1c48398246619cc5595009

**Comment by seveibar** [comment]
In the network tab of developer tools, the failing request is a request to `POST https://moufette.universaldatatool.com/graphql`, fails with 400 error. Here's the response:

```
{"errors":[{"message":"Variable \"$property\" of required type \"ID!\" was not provided.","locations":[{"line":1,"column":39}],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["GraphQLError: Variable \"$property\" of required type \"ID!\" was not provided.","    at _loop (/home/ec2-user/moufette/node_modules/graphql/execution/values.js:94:17)","    at coerceVariableValues (/home/ec2-user/moufette/node_modules/graphql/execution/values.js:121:16)","    at getVariableValues (/home/ec2-user/moufette/node_modules/graphql/execution/values.js:50:19)","    at buildExecutionContext (/home/ec2-user/moufette/node_modules/graphql/execution/execute.js:206:61)","    at executeImpl (/home/ec2-user/moufette/node_modules/graphql/execution/execute.js:104:20)","    at Object.execute (/home/ec2-user/moufette/node_modules/graphql/execution/execute.js:63:35)","    at /home/ec2-user/moufette/node_modules/apollo-server-core/dist/requestPipeline.js:249:48","    at Generator.next (<anonymous>)","    at /home/ec2-user/moufette/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","    at new Promise (<anonymous>)","    at __awaiter (/home/ec2-user/moufette/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)","    at execute (/home/ec2-user/moufette/node_modules/apollo-server-core/dist/requestPipeline.js:228:20)","    at Object.<anonymous> (/home/ec2-user/moufette/node_modules/apollo-server-core/dist/requestPipeline.js:176:42)","    at Generator.next (<anonymous>)","    at fulfilled (/home/ec2-user/moufette/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)"]}}}]}
```

**Comment by jamalx31** [comment]
Hi @seveibar 
sorry for the late reply. did you manage to solve this issue?
if not I promise I will look into it this weekend

**Comment by seveibar** [comment]
We didn't, we just left the defaults in!
